[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "a40133b69fbd73ee655606a9bf5f8b9b9bf758dd"
  source = "github.com/prometheus/client_golang"

[[override]]
  name = "github.com/containers/storage"
  revision = "1e5ce40cdb84ab66e26186435b1273e04b879fef"
  source = "github.com/containers/storage"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"
  source = "github.com/docker/distribution"

[[constraint]]
  name = "github.com/GoogleCloudPlatform/container-diff"
  branch = "master"
  source = "github.com/GoogleCloudPlatform/container-diff"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "b1a1234c60cf87048814aa37da523b03a7b0d344"
  source = "github.com/docker/docker"

[[constraint]]
  name = "github.com/genuinetools/amicontained"
  version = "0.4.0"
