timeout: 1800s

steps:
  # Set up builder for muti-arch builds.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:v0.7']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'show-target-build-platforms'

  # First, build kaniko
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile",
           "-t", "gcr.io/kaniko-project/executor:$TAG_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kaniko-project/executor:$TAG_NAME",
           "gcr.io/kaniko-project/executor:latest"]

  # Then, we want to build kaniko:debug
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile_debug",
           "-t", "gcr.io/kaniko-project/executor:debug-$TAG_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kaniko-project/executor:debug-$TAG_NAME",
           "gcr.io/kaniko-project/executor:debug"]

  # Then, we want to build the cache warmer
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile_warmer",
           "-t", "gcr.io/kaniko-project/warmer:$TAG_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kaniko-project/warmer:$TAG_NAME",
           "gcr.io/kaniko-project/warmer:latest"]

  # Finally executor:slim image
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile_slim",
           "-t", "gcr.io/kaniko-project/executor:$TAG_NAME-slim", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/kaniko-project/executor:$TAG_NAME-slim",
           "gcr.io/kaniko-project/executor:slim"]


images: ["gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:${COMMIT_SHA}",
         "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:latest",
         "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:${COMMIT_SHA}-slim",
         "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:slim",
         "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:debug-${COMMIT_SHA}",
         "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:debug",
         "gcr.io/$PROJECT_ID/${_WARMER_IMAGE_NAME}:latest",
         "gcr.io/$PROJECT_ID/${_WARMER_IMAGE_NAME}:${COMMIT_SHA}"]

options:
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'

substitutions:
  _EXECUTOR_IMAGE_NAME: executor
  _WARMER_IMAGE_NAME: warmer
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64,linux/s390x'
