timeout: 1800s

steps:
  # Set up builder for muti-arch builds.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:v0.7']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--use', '--platform', '${_DOCKER_BUILDX_PLATFORMS}']
    id: 'create-builder'

  # First, build kaniko
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile",
           "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$COMMIT_SHA", "--push", "." ]

  # Finally executor:slim image
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile_slim",
           "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$COMMIT_SHA-slim", "--push", "."]

options:
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'

substitutions:
  _EXECUTOR_IMAGE_NAME: executor
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64,linux/s390x'
