timeout: 1800s

steps:
  # Set up builder for muti-arch builds.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:v0.7']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--use', '--platform', '${_DOCKER_BUILDX_PLATFORMS}']
    id: 'create-builder'

  # Then, we want to build kaniko:debug
  - name: "gcr.io/cloud-builders/docker"
    args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile_debug",
           "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$COMMIT_SHA-debug",
           "--push", "."]


options:
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'

substitutions:
  _EXECUTOR_IMAGE_NAME: executor
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm64,linux/s390x'
