name: Integration tests (Layers)

# Triggers the workflow on push or pull request events
on: [pull_request]

concurrency:
  group: int-test-layers-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-executor:
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run integration-test-layers
      run: |
        make travis-setup
        make minikube-setup
        make integration-test-layers
