name: Integration Tests Misc

# Triggers the workflow on push or pull request events
on: [push, pull_request]

concurrency:
  group: int-test-mis-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-executor:
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      TRAVIS_REPO_SLUG: ${{ github.repository }}
      TRAVIS_BRANCH: ${{ github.head_ref }}
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print Travis ENV vars
        run: |
          echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"
          echo "TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}"
          echo "TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"

      - name: Run integration-test-misc
        run : |
          make travis-setup
          make integration-test-misc